# Generated by Django 3.1.6 on 2021-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reytings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subscribers', models.IntegerField()),
                ('views', models.IntegerField()),
                ('vaqt', models.IntegerField()),
                ('link', models.TextField()),
            ],
        ),
    ]
