# Generated by Django 3.1.6 on 2021-06-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerreytings', '0002_blogposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=2020),
            preserve_default=False,
        ),
    ]
