# Generated by Django 3.1.6 on 2021-06-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerreytings', '0003_blogposts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='date',
        ),
    ]
